import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./components/Authprovider/Authprovider";
import {FileProvider} from "./components/fileContext";
import Navbar from "./components/navbar/navbar"; 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <FileProvider>
            {/* <Navbar/> */}
            {children}
          </FileProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
